[workspace]
authors = ["tc-mustang <rlozano.fi@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "Proteins"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
py3dmol = ">=2.5.2,<3"
ipykernel = ">=6.30.1,<7"
requests = ">=2.32.5,<3"
